source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

# 使用framework
use_frameworks!

# 忽略警告
inhibit_all_warnings!

# 三方库
def thirdPods
  
end

# 基础组件库
def basePods
  # 基础代理
  pod 'LQGBaseAppDelegate'
end

# 工具层
def toolPods
  # 中间件
  pod 'LQGCTMediator'
end

# 业务层
def businessPods
  # 用户管理
  pod 'LQGUser', :git => 'https://github.com/LuoJianGitHub/LQGUser.git', :tag => '1.0.0'
  # 主题
  pod 'LQGUIStyle', :git => 'https://github.com/LuoJianGitHub/LQGUIStyle.git', :tag => '1.0.0'
  
  # 签名
  pod 'LQGSign', :git => 'https://github.com/LuoJianGitHub/LQGSign.git', :tag => '1.0.0'
  pod 'LQGSign_Category', :git => 'https://github.com/LuoJianGitHub/LQGSign_Category.git', :tag => '1.0.0'
  # 用户中心
  pod 'LQGUserCenter', :path => '../'
end

targets = ['LQGUserCenter_Example']

targets.each do |t|
  target t do
    thirdPods
    basePods
    toolPods
    businessPods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # do your self something
    end
  end
end
